# Generated by Django 4.1.4 on 2022-12-06 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentary',
        ),
    ]
